version: '3.5'
services:
  redisserver:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
  proxyserver:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - redisserver
    environment:
      - REDIS_SERVER_ADDR=redisserver
      - REDIS_SERVER_PORT=6379
      - CACHE_EXPIRY_TIME=300
      - CACHE_CAPACITY=5
      - CONCURRENCY_LIMIT=5

